name: Remote update execution

on: [push] # This workflow runs on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.2.0 # Use the action
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: | # Use the pipe | to run multiple commands
          cd ~/app/safespace/
          #cp ./env.production ./env
          echo "Commands executed successfully!"
